### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by cauerego** [austinhuang0131/austinhuang0131.github.io#12]
on "no", before cloudflare

https://austinhuang.me/

cheers!

**Comment by austinhuang0131** [comment]
fixed in https://github.com/austinhuang0131/austinhuang0131.github.io/commit/4b5f839916720586a7ab3e2f3cc7063189f34ca1

seems like that link was [taken down](https://blog.codeberg.org/on-the-cloudflare-tor-takedown.html) though I just linked an introductory page and was not aware that they doxxed people

**Comment by cauerego** [comment]
sorry, what was in that page?

why haven't you just replaced it by this new link (since they seem to be about the exact same thing)?

on another note... #13

**Comment by austinhuang0131** [comment]
https://git.nogafam.es/deCloudflare/deCloudflare/src/branch/master/readme/en.md

But then I'm not gonna endorse naming cloudflare users, all I care is that I don't use it

**Comment by cauerego** [comment]
thanks! very nice page. 😁

i was already abandoning cloudflare. this certainly helps me to accelerate the process and put a period on it.

**Comment by austinhuang0131** [comment]
For others:

A Mastodon bot affiliated with deCloudflare sent me (and @cauerego) a DM linking their statement.

It is my personal decision to not use Cloudflare at my personal website, and at this point I regret supporting specific anti-Cloudflare efforts. As such, I will no longer promote any such effort on my website.

It is right to go against Cloudflare, but only *within reasonable constraints*, which most certainly does not include witch-hunting.

**Comment by cauerego** [comment]
funny enough, i can't see that link due to 502 on banana.dog cloudflare! 🤣

![Screenshot_20211114-092120](https://user-images.githubusercontent.com/560418/141675095-a57b0a2c-22b0-46e2-868b-167da4581190.png)

love your decision of removing that link as well.

thanks for sharing!! 🥰
