### ISSUE TITLE
about choosing the good side...

### ISSUE THREAD

**Issue by cauerego** [austinhuang0131/austinhuang0131.github.io#13]
# no cloudflare

all i know about cloudflare issues is what i read in your link http://www.crimeflare.org:82/

> 
> CloudFlare Watch
>  
> 
> CloudFlare is a venture-funded startup that routes around Internet abuse by  
> acting as a reverse proxy. They also encourage illegality by allowing hackers,
> DDoSers, cyberbullies, and copyright pirates to hide behind their servers.
> By 2015, CloudFlare was even protecting websites that recruited for ISIS.
> 
> Uncovering bad guys hiding behind CloudFlare
> 
> Is CloudFlare affected by the EU's GDPR?
> 
> NYT: CloudFlare protects child-abuse porn sites
> 
> CloudFlare attracts "repeat infringers"
> 
> CloudFlare's half-baked SSL
> 
> Is CloudFlare a honey pot?
> 
> CloudFlare's wonky nameserver setup
> 
> Some domains that recently used CloudFlare
> 
> Where in the world are those CloudFlare domains?
> 
> The gang at CloudFlare aids and abets cybercriminals
> 
> 
> 
> 
> Carders love CloudFlare
> 
> CloudFlare's growth is not so amazing
> 
> CloudFlare seeks riches through anarchy
> 
> Spamhaus blocks CloudFlare's IP ranges
> 
> Those laughable CloudFlare terms of service
> 
> Dear Damon Billian: We're not as stupid as you think!
> 
> CloudFlare still chummy with ex-cons from LulzSec
> 

and i only clicked on 2 links there for sampling...

but from that page alone, this looks to be like an infantile attack on someone (cloudflare in this case) who's just trying their best to keep things free and open, with no restrictions.

i get it. free speech can't be so free as to allow flooding, for instance, to silence the right of others to free speech. openness face similar issues. language is paradoxical. but paradoxes are language bugs.

technically, at least, cloudflare seem to have just one major issue from my perspective: it's not open sourced. i guess, i haven't even checked. this, by itself, is enough to blacklist them... but i would love to see an open sourced nameserver! i never seen one.

the politics of gdpr and governments are technically wrong, most of the time. we definitely need filters, and privacy. but above those, we need data consistency, backups, and every single data point to be public. for some stupid reason, almost all politics (which is made by every single citizen) fails to see this.

anyway...

# yes github

github is owned by microsoft. it promotes open source but it doesn't open its own source.

if you want to be on the good side, you should worry about this way before name servers. 😏

# sorry not really tl;dr;

hope this is at least somewhat informative to you!

if you think this was simply me venting, just close it with no comments. i'll be fine.

thanks for reading! 😘

**Comment by austinhuang0131** [comment]
> but i would love to see an open sourced nameserver! i never seen one.

https://desec.io, I use that.

Also I am objecting more to Cloudflare being a *reverse proxy* (ie. they can see and manipulate your traffic) rather than nameserver (so tbh the deCloudflare page is better, but oh well)

**Comment by cauerego** [comment]
thanks for the pointers!

but since you also replied about cloudflare... (yes, that decloudflare page on #12 was very informative!)

could you also comments on why github?

**Comment by austinhuang0131** [comment]
popularity

but also because github isn't *that* bad
